---
- name: Install Nginx (Debian example)
  package:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"

- name: Configure Nginx to serve bootstrap.sh
  template:
    src: nginx-bootstrap.conf.j2
    dest: "/etc/nginx/conf.d/bootstrap.conf"
    mode: '0644'
  notify: Reload Nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

# Handlers
- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
