---
- include_tasks: "{{ item }}"
  loop:
    - ensure-installed.yml
    - tmux-config.yml
    - set-zsh.yml
    - ubuntu-disable-cloud-init.yml
    - ubuntu-motd.yml
  when: ansible_distribution not it ["Raspbian", "Raspberry Pi OS"]
