---
# Keyserver Role: Provision the keyserver machine to generate its own ECDSA SSH key pair
# and serve the private key securely via Nginx.
# It also prints the public key so that you can add it to GitHub.

# - import_tasks: vault.yml
- include_tasks: "{{ item }}"
  loop:
    - keyserver.yml
    - static_ip.yml
  when: ansible_distribution not it ["Raspbian", "Raspberry Pi OS"]

- include_tasks: raspi-keyserver.yml
  when: ansible_distribution in ["Raspbian", "Raspberry Pi OS"]
