# Inventory that makes an alias for localhost that uses Python3
# localhost-py3 ansible_host=localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[localhost]
127.0.0.1

[localhost:vars]
ansible_python_interpreter=/usr/bin/python3

[popos]
192.168.50.161
