---
# tasks to complete before running roles
- hosts: localhost
  tags: always
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  tasks:
  - name: install packages
    package:
      name:
        - tmux
        - htop
        - vim
        - fd-find
        - rsync
        - exa
        - bat
        - ripgrep
        - zsh
        - nodejs
        - zoxide
        - fzf
        - xclip
        - git
        - qemu-guest-agent
        - awscli

  - name: add alan1 user
    tags: always
    user:
      name: alan1
      groups: root

  - name: change user shell to zsh
    become: yes
    user:
      name: alan1
      shell: /bin/zsh

  - name: change user shell to zsh
    become: yes
    user:
      name: root
      shell: /bin/zsh

  - name: install starship
    ansible.builtin.shell:
      cmd: curl -sS https://starship.rs/install.sh | sh -s -- -y
      warn: False

  - name: Clone antidote repository for alan1
    git:
      repo: https://github.com/mattmc3/antidote.git
      dest: /home/alan1/.antidote
      clone: yes
      update: yes

  - name: Clone antidote repository for root
    git:
      repo: https://github.com/mattmc3/antidote.git
      dest: /root/.antidote
      clone: yes
      update: yes

  - name: copy .zshrc file
    copy:
      src: dotfiles/.zshrc
      dest: /home/alan1/.zshrc
      owner: alan1
      group: alan1

  - name: copy .tmux.conf file
    copy:
      src: dotfiles/.tmux.conf
      dest: /home/alan1/.tmux.conf
      owner: alan1
      group: alan1

  - name: copy .tmuxline.conf file
    copy:
      src: dotfiles/.tmuxline.conf
      dest: /home/alan1/.tmuxline.conf
      owner: alan1
      group: alan1

  - name: copy .zsh_plugins.txt file
    copy:
      src: dotfiles/.zsh_plugins.txt
      dest: /home/alan1/.zsh_plugins.txt
      owner: alan1
      group: alan1

  - name: copy .vimrc file
    copy:
      src: dotfiles/.vimrc
      dest: /home/alan1/.vimrc
      owner: alan1
      group: alan1

  - name: copy .aliases file
    copy:
      src: dotfiles/.aliases
      dest: /home/alan1/.aliases
      owner: alan1
      group: alan1

  - name: copy .zshrc file
    copy:
      src: dotfiles/.zshrc
      dest: /root/.zshrc
      owner: root
      group: root

  - name: copy .tmux.conf file
    copy:
      src: dotfiles/.tmux.conf
      dest: /root/.tmux.conf
      owner: root
      group: root

  - name: copy .tmuxline.conf file
    copy:
      src: dotfiles/.tmuxline.conf
      dest: /root/.tmuxline.conf
      owner: root
      group: root

  - name: copy .zsh_plugins.txt file
    copy:
      src: dotfiles/.zsh_plugins.txt
      dest: /root/.zsh_plugins.txt
      owner: root
      group: root

  - name: copy .vimrc file
    copy:
      src: dotfiles/.vimrc
      dest: /root/.vimrc
      owner: root
      group: root

  - name: copy .aliases file
    copy:
      src: dotfiles/.aliases
      dest: /root/.aliases
      owner: root
      group: root

  - name: add ansible user
    user:
      name: ansible
      system: yes

  - name: Creates sudoers.d directory
    file:
      path: /etc/sudoers.d
      state: directory

  - name: Creates zsh directory alan1
    file:
      path: /home/alan1/.cache/zsh/
      state: directory
      user: alan1
      group: alan1

  - name: Creates zsh directory for root
    file:
      path: /root/.cache/zsh/
      state: directory

  - name: Creates zsh history file alan1
    file:
      path: /home/alan1/.cache/zsh/history
      state: touch
      user: alan1
      group: alan1

  - name: Creates zsh history file for root
    file:
      path: /root/.cache/zsh/history
      state: touch

  - name: set up sudo for alan1
    copy:
      src: sudoers/alan1
      dest: /etc/sudoers.d/alan1
      owner: root
      group: root
      mode: 0440

  - name: set up sudo for ansible user
    copy:
      src: sudoers/ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/sparkleHazard/ansible.git
