---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - tmux
        - htop
        - vim
        - fd-find
        - rsync
        - exa
        - bat
        - ripgrep
        - zsh
        - nodejs
        - zoxide
        - fzf
        - xclip
        - git
        - qemu-guest-agent
        - awscli
