---
brew_cask_packages:
  - dropbox
  - firefox
  - google-chrome
  - iterm2
  - kitty
  - keepassxc
  - bitwarden
  - displaylink
  - font-fira-code-nerd-font
  - font-jetbrains-mono-nerd-font
  - home-assistant
  - jump-desktop-connect
  - karabiner-elements
  - mullvadvpn
  - obsidian
  - qmk-toolbox
  - raspberry-pi-imager
  - raycast
