---
- name: Apply base and common configuration
  hosts: localhost
  gather_facts: yes
  roles:
    - homebrew
    - base
    - common

- name: Apply role-specific configuration
  hosts: localhost
  gather_facts: yes
  tasks:
    - include_role:
        name: keyserver
      when: host_role | default('base') == "keyserver"
    - include_role:
        name: webserver
      when: host_role | default('base') == "webserver"
  become: yes

- name: Provision MacOS-Specific Configuration
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Include macos role if running on Darwin
      include_role:
        name: macos
      when: ansible_system == "Darwin"
