---
- name: Apply base Linux configuration
  hosts: localhost
  gather_facts: True
  tasks:
    - name: Include base Linux roles
      include_role:
        name: "{{ item }}"
      loop:
        - homebrew
        - base
        - dotfiles
      when: host_role | default('base') == "base" and ansible_system == "Linux"

- name: Apply keyserver configuration
  hosts: localhost
  gather_facts: True
  tasks:
    - include_role:
        name: keyserver
      when: host_role | default('base') == "keyserver" and ansible_system == "Linux"

- name: Apply base MacOS Configuration
  hosts: localhost
  gather_facts: True
  tasks:
    - name: Include base MacOS roles
      include_role:
        name: "{{ item }}"
      loop:
        - macos
        - homebrew
        - base
        - dotfiles
      when: (host_role | default('base')) == 'base' and ansible_system == "Darwin"
