---
- name: Apply base and common configuration
  hosts: localhost
  gather_facts: yes
  roles:
    - base
    - common

- name: Apply role-specific configuration
  hosts: localhost
  gather_facts: yes
  tasks:
    - include_role:
        name: keyserver
      when: host_role | default('base') == "keyserver"
    - include_role:
        name: webserver
      when: host_role | default('base') == "webserver"

- name: Debug host_role variable
  hosts: localhost
  gather_facts: yes
  tasks:
    - debug:
        msg: "host_role is {{ host_role | default('base') }}"
